### ISSUE TITLE
"Computer Modern Serif" font can't apply to chinese charactor 

### ISSUE THREAD

**Issue by luobo202254** [LucasVadilho/heyo-hugo-theme#2]
Hello, I really like this theme, but I am a Chinese user, and the Chinese charactor cannot use  "Computer Modern Serif"  font. So could you give me some ideas to solve this question? @LucasVadilho

**Comment by LucasVadilho** [comment]
Hey, thanks!

I'm going to look into it :) @luobo202254, could you help me and provide some text that isn't being rendered?

**Comment by luobo202254** [comment]
<img width="710" alt="render" src="https://github.com/LucasVadilho/heyo-hugo-theme/assets/54588202/0221e6d4-aeae-406a-8e1b-e05901e4a9de"><br />
The  image shows the rendered effect.
You see, Chinese characters  look a bit bold， I think it's because the font does not support it.
However,  in the code section,  both have a similar thickness. Maybe code section use the default font.
 I searched `CMU Serif`font at this [website](https://www.cufonfonts.com/font/cmu-serif),  then not found  it support Chinese in its `Supported Languages` list.

@LucasVadilho You can test with the following text：
> This is python manual, 这是python的帮助手册

**Comment by LucasVadilho** [comment]
Ohh, I see it now. Thought that some characters were not being rendered.

Yes, you're right, the font does not support CJK glyphs. We can check that in the Dev tools:
![image](https://github.com/LucasVadilho/heyo-hugo-theme/assets/7459017/6aed0956-98ce-4663-a8ff-d43461941bae)

I just tried searching a bit for a version with CJK glyphs, no luck so far for a single font with everything :/

However, looking at some of [Overleaf's documentation](https://www.overleaf.com/learn/latex/Chinese), I found a couple of fonts that may play well with Computer Modern.

In the image below there are some variations, what do you think about them?

![image](https://github.com/LucasVadilho/heyo-hugo-theme/assets/7459017/b32a0f48-ceea-422b-9bdb-7a11808f8fa5)

If you'd like to do some exploration with other examples, you can clone and build the `cjk` branch with the following (the post is in `content/en/post/cjk.md`):

```sh
git clone -b cjk git@github.com:LucasVadilho/heyo-hugo-theme.git heyo
cd heyo/exampleSite && hugo server --themesDir ../..
```

**Comment by LucasVadilho** [comment]
Just found [this one](https://fonts.google.com/noto/specimen/Noto+Serif+TC) too. Will add it to the test page later (@luobo202254, if you have other suggestions feel free to point me to them :))

**Comment by luobo202254** [comment]
@LucasVadilho  Thanks for your time and effort :)
I've tried it, and the `Computer Modern Serif, FandolKai-Regular` font looks quite nice.
<br />

> Just found [this one](https://fonts.google.com/noto/specimen/Noto+Serif+TC) too. Will add it to the test page later (@luobo202254, if you have other suggestions feel free to point me to them :))

Chinese is divided into Simplified Chinese and Traditional Chinese. I often use Simplified Chinese, but this font lacks sufficient support for Simplified Chinese.
<img width="543" alt="test" src="https://github.com/LucasVadilho/heyo-hugo-theme/assets/54588202/536bb07f-6ee5-490b-b55d-37f2dd41e74f">

**Comment by luobo202254** [comment]
Oh, I did not notice the font name is `Noto Serif Traditional Chinese`.
The `Noto Serif` font family seems support most CJK Characters. 
However, using one of the fonts would likely be insufficient to support all languages., such as `Simplified Chinese` ,`Traditional Chinese` , `Japanese`
So is it possible to provide an option in the configuration file to allow users to define the font used for their own language?

**Comment by LucasVadilho** [comment]
> @LucasVadilho Thanks for your time and effort :)
I've tried it, and the Computer Modern Serif, FandolKai-Regular font looks quite nice.

No problem! I also liked this combination the best, so I'll make it the default for the theme :)

---

> So is it possible to provide an option in the configuration file to allow users to define the font used for their own language?

Yes! In `config.toml`, under `[params]`, there's `customCss`, on that param you can point to a CSS file that will override the defaults.

For example, let's say you have `customCSS = ['customCss/my-font-family.css']` in `config.toml` and you create a file at `exampleSite/static/customCss/my-font-family.css` with the following.

```css
* {
    font-family: 'sans serif', 'Noto Serif TC';
}
```

The result would be:

![image](https://github.com/LucasVadilho/heyo-hugo-theme/assets/7459017/f8f2eb86-e2d0-48ee-959e-e13eb7e9a946)

**Comment by luobo202254** [comment]
That's great!  🌹

**Comment by LucasVadilho** [comment]
Thanks for the help @luobo202254! lmk if you spot anything else weird :)

I think #3 closes this.
